CREATE TABLE clientes (
    id bigint generated by default as identity,
    nome varchar(255),
    cpf varchar(14),
    data_nascimento varchar(10),
    endereco varchar(255),
    numero_contato varchar(15),
    email varchar(255),
    info_pagamento varchar(255)
);

INSERT INTO clientes(nome, cpf, data_nascimento, endereco, numero_contato, email, info_pagamento) VALUES
('George Foreman', '123.456.786-09', '10/01/1949', 'rua XYZ, bairro ABC, 100, Texas-EUA', '(10) 98762-4455', 'gforeman@email.com', 'Cartao de Credito'),
('Mike Tyson', '986.234.786-09', '30/06/1966', 'rua XYZ, bairro ABC, 100, Nova York-EUA', '(12) 98367-1235', 'mtyson@email.com', 'Cartao de Credito'),
('Manny Pacquiao', '098.789.391-09', '17/12/1978', 'rua XYZ, bairro ABC, 100, Filipinas', '(13) 43579-0809', 'mpacquiao@email.com', 'Cartao de Debito'),
('Juan Manuel Márquez', '667.166.908-99', '23/08/1973', 'rua XYZ, bairro ABC, 100, Mexico', '(14) 67899-8800', 'jmmarquez@email.com', 'Cartao de Credito');
